version: '3.5'

services:
  backend:
    build:
      context: docker/
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/etc/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      # external:internal
      - 80:80

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    # volumes:
      # - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

